### PR TITLE
fix: increase versions to use latest and fix label lookup on namespaces

### PR DESCRIPTION
**Pull request by Skarlso**
## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)
> Remove if not applicable

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added e2e-tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for e2e-tests

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by souleb — APPROVED** [review]

**Comment by Skarlso** [comment]
hum, sometimes the e2e setup fails because of a timeout... 🤔

**Comment by Skarlso** [comment]
huh, timed out again, will run locally

**Comment by Skarlso** [comment]
Oh fuck. This was buried in the logs... :D 

```
 ./hack/prime_test_cluster.sh: line 32: ./bin/mkcert: No such file or directory
```

**Comment by Skarlso** [comment]
Okay, I added the missing mkcert definition. This didn't stop this thing from dying before BTW. So I'm not sure if this is going to do anything, hahaha. Let's see...

**Pull request merged**
